---
title: "Family Routines Module"
date: "Last updated: 4/07/2023"
output: 
 html_document:
    css: "custom2.css"
---
```{r packages, echo=FALSE, warning=FALSE, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(knitr)
library(tidyr)
library(kableExtra)
library(stringr)
library(dplyr)
options(knitr.table.format = "html", knitr.kable.NA = '') 
```

```{r read data, echo=FALSE}
data.raw <- read_excel("Data/FamilyRoutinesCC.xlsx")
data.raw$Answers <- gsub(pattern = "\n", replacement = "<br/>", x = data.raw$Answers)
data.raw$Question <- gsub(pattern = "\n", replacement = "<br/>", x = data.raw$Question)
data.raw$'Source Link' <- paste0("<a href='",data.raw$'Source Link',"'>", data.raw$'Source Link',"</a>")
```

Instructions: In this set of questions we would like to know what family routines looked like before the COVID-19 pandemic compared to current routines families have.

Occurrence indicates what weeks the questions in this module were asked. 

```{r display data, echo=FALSE}

DT::datatable(data.raw, class = 'cell-border stripe hover',  rownames = F, filter = 'top', editable = TRUE, extensions = 'Buttons',  options = list(
  dom = 'BFrtip',
  buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
), escape = FALSE)

```
