---
title: "R3 Question Bank Dashboard"
date: "Last Updated: 8/31/2020"
output: 
  html_document:
    theme: cosmo
---
```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(
  comment = NA,
  warning = FALSE,
  message = FALSE)
```

This site hosts a list of questions asked as a part of the RAPID-EC project. All efforts were taken to ensure the accuracy of the question sources.

Below is a list of when special topics were introduced to the survey.

If there are any questions or concerns, please do not hesitate to reach out to the RAPID-EC team. 

```{r packages, echo=FALSE, warning=FALSE, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(knitr)
library(tidyr)
library(kableExtra)
library(stringr)
library(dplyr)
options(knitr.table.format = "html", knitr.kable.NA = '') 
```

```{r read data, echo=FALSE}
data.raw <- read_excel("Data/SurveyTrackingCalendar.xlsx")

```

```{r display data, echo=FALSE}

DT::datatable(data.raw, class = 'cell-border stripe hover',  rownames = F,  options = list(
  pageLength = 25, autoWidth = TRUE
))

```
