---
title: "Staffing and Retention Module"
date: "Last updated: 12/20/2022"
output: 
 html_document:
    css: "custom2.css"
---
```{r packages, echo=FALSE, warning=FALSE, include=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(knitr)
library(tidyr)
library(kableExtra)
library(stringr)
library(dplyr)
library(htmltools)
library(DT)
options(knitr.table.format = "html", knitr.kable.NA = '')
```

```{r read data, echo=FALSE}
data.raw <- read_excel("Data/StaffingandRetentionCC.xlsx")
data.raw$Answers <- gsub(pattern = "\n", replacement = "<br/>", x = data.raw$Answers)
data.raw$Question <- gsub(pattern = "\n", replacement = "<br/>", x = data.raw$Question)
data.raw$'Source Link' <- paste0("<a href='",data.raw$'Source Link',"'>", data.raw$'Source Link',"</a>")
```

```{r display data, echo=FALSE}

header.style <- "th { font-family: 'Arial'; font-weight: bold; color: black; background-color: #f1d310;}"
header.names <- c(" ", colnames(data.raw))
# The container parameter allows us to design the header of the table
# using CSS
my.container <-  withTags(table(
    style(type = "text/css", header.style),
    thead(
        tr(
                lapply(header.names, th, style = "text-align: center; border-right-width: 1px; border-right-style: solid; border-right-color: white; border-bottom-width: 1px; border-bottom-style: solid; border-bottom-color: white")
        )
    )
))

my.table = DT::datatable(data.raw, class = 'cell-border stripe hover',  rownames = T, 
  width = '100%', height = '100%', extensions = 'Buttons', container = my.container,  options = list(
  dom = 'Bfrtip',
  buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
), escape = FALSE)

my.table

```
